version: '3'
services:
#  db:
#
#  symfony_app:
#    depends_on:
#      - db
  nginx:
    container_name: nginx
    image: nginx:custom
    build: ./docker/nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html
    command: [nginx, '-g', 'daemon off;']
    # command: [nginx-debug, '-g', 'daemon off;'] # debug
    depends_on:
      - php
  php:
    container_name: php
    build:
     context: ./docker/php
     args:
       LINUX_USER: ${LINUX_USER}
    volumes:
      - ./app:/var/www/html
      - ./docker/php/config/${APP_ENV}/php.ini:/usr/local/etc/php/php.ini