version: '3'

services:
#  db:
#
#  symfony_app:
#    depends_on:
#      - db
  nginx:
    build: ./docker/nginx
    image: nginx:custom
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/html:/usr/share/nginx/html
    command: [nginx, '-g', 'daemon off;']
  php:
    image: php:8.1.15-fpm-alpine3.17
    volumes:
      - ./docker/nginx/html:/var/www/html