version: '3'

services:
#  db:
#
#  symfony_app:
#    depends_on:
#      - db
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      -   nginx_conf_volume:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - symfony_app

volumes:
  nginx_conf_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /./docker/nginx/default.local.conf